version: "3"

services:
  crucial-crawler:
    image: crucial_crawler:v1.0.0
    restart: always
    container_name: crucial_crawler
    volumes:
      - ../logs/:/src/logs/
      - ../.env:/src/.env
    network_mode: host
